version: "3"
services:
  rustbox:
    container_name: rustbox
    image: jayeve/rustbox
    environment:
      - DOCKER_HOST=tcp://socat:2375
    links:
      - socat
    volumes:
      - ~/.gitconfig:/home/dev/.gitconfig:ro
      - ~/.work_functions.bash:/home/dev/.work_functions.bash:ro
      - ~/.ssh/id_rsa:/home/dev/.ssh/id_rsa:ro
  socat:
     image: bpack/socat
     command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
     volumes:
        - /var/run/docker.sock:/var/run/docker.sock
     expose:
        - "2375"
