version: "3"
services:
  scalabox:
    container_name: scalabox
    image: jayeve/scalabox:${TAG}
    environment:
      - DOCKER_HOST=tcp://socat:2375
    links:
      - socat
    volumes:
      - ~/.cache/coursier/v1:/root/.cache/coursier/v1
      - ~/.ivy2:/root/.ivy2
      - ~/scratch:/home/dev/scratch
      - ~/.gitconfig:/home/dev/.gitconfig:ro
      - ~/.work_functions.bash:/home/dev/.work_functions.bash:ro
      - ~/.ssh/id_rsa:/home/dev/.ssh/id_rsa:ro
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
  socat:
     image: bpack/socat
     command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
     volumes:
        - /var/run/docker.sock:/var/run/docker.sock
     expose:
        - "2375"
